Add tabby-codellama-7B
premAI-io/prem-registry pull request #76
Opened 2023-09-22 12:44 UTC by Janaka-Steph

Missing "Hardware Requirements" and "Limitations and Biases" sections in readme.

2023-09-22 12:47 UTC, filopedraz requested changes

2023-09-22 12:47 UTC, filopedraz commented on coder-tabby-codellama-7b/manifest.json
> +    "command": "serve --model TabbyML/CodeLlama-7B --device cuda",
Cuda?

2023-09-22 12:47 UTC, filopedraz commented on coder-tabby-codellama-7b/manifest.json
> +    "volumePath": "/data",
Is volumePath necessary?

2023-09-25 13:31 UTC, Janaka-Steph commented on coder-tabby-codellama-7b/manifest.json
> +    "command": "serve --model TabbyML/CodeLlama-7B --device cuda",
`device` takes either `cuda`, `cpu` or `metal`.
It seems that `--device metal` is appropriate for Apple M1/M2 https://github.com/TabbyML/tabby/blob/cc83e4d2691f5438a236d4bb735ea6b9da436234/website/docs/extensions/troubleshooting.md?plain=1#L81
But I am not sure which one is best to use.

2023-09-25 13:32 UTC, Janaka-Steph commented on coder-tabby-codellama-7b/manifest.json
> +    "volumePath": "/data",
I guess not

2023-09-25 14:15 UTC, tiero commented on coder-tabby-codellama-7b/manifest.json
> +    "command": "serve --model TabbyML/CodeLlama-7B --device cuda",
yes Metal only, as we are on Mac only. Cuda is server/linux

2023-09-25 17:41 UTC, filopedraz commented on coder-tabby-codellama-7b/manifest.json
> +    "volumePath": "/data",
@tiero how do we handle volumes for binaries? Same issue will appear for vector stores.

2023-09-26 20:17 UTC, filopedraz commented on coder-tabby-codellama-7b/manifest.json
> +    "volumePath": "/data",
Makes sense

2023-09-27 07:07 UTC, merged